server:
  # 服务器的HTTP端口，默认为8080
  port: 8081

spring:
  datasource:
    # 主库数据源
    driverClassName: org.postgresql.Driver
    hikari:
      auto-commit: false
      idle-timeout: 60000
      minimum-idle: 5
      leak-detection-threshold: 240000
      maximum-pool-size: 100
      connection-timeout: 30000
      max-lifetime: 30000

    # jdbc 所有参数配置参考 https://lionli.blog.csdn.net/article/details/122018562
    # rewriteBatchedStatements=true 批处理优化 大幅提升批量插入更新删除性能(对数据库有性能损耗 使用批量操作应考虑性能问题)
    url: jdbc:postgresql://lzynb.com.cn:15432/lzy?useUnicode=true&characterEncoding=utf8&useSSL=true&autoReconnect=true&reWriteBatchedInserts=true
    username: course-design
    password: course-design2023
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


aria2:
  default_save_path: ./res
  download_url: 127.0.0.1
  download_port: 6800
  secret: secret
  json_rpc_version: 2.0