server:
    port: 12138

spring:
    application:
        name: xy-schedule-task-module
    profiles:
        active: dev
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
    # 数据库配置
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/xy_schedule_task
        username: postgres
        password: j1101714214
    redis:
        port: 6379
        host: localhost
        jedis:
          pool:
              max-active: 8
              max-wait: 5000    # 最大阻塞等待时间5000ms
              max-idle: 8
              min-idle: 0
    quartz:
        properties:
            org:
                quartz:
                    scheduler:
                        # 集群名，区分同一系统的不同实例，若使用集群功能，则每一个实例都要使用相同的名字
                        instanceName: SERVICEX-SCHEDULER-INSTANCE
                        # 若是集群下，每个instanceId必须唯一
                        instanceId: AUTO
                    threadPool:
                        #一般使用这个便可
                        class: org.quartz.simpl.SimpleThreadPool
                        #线程数量，不会动态增加
                        threadCount: 20
                        threadPriority: 5
                        threadsInheritContextClassLoaderOfInitializingThread: true


mybatis-plus:
    type-enums-package: edu.whu.model.common.enumerate

xy-nas-tools:
    knife4j:
        base-package: edu.whu.controller
        title: xyNasTools任务调度服务在线API文档
        description: xyNasTools任务调度服务在线API文档, 用于前后端联调
        version: 1.0
knife4j:
    enable: true
    basic:
        enable: true  #进入界面是否需要账号密码
        username: admin
        password: 123456
