server:
    port: 12138

spring:
    application:
        name: xy-schedule-task-module
    profiles:
        active: dev
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
    # 数据库配置
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/xy_schedule_task
        username: postgres
        password: j1101714214
    redis:
        port: 6379
        host: localhost
        jedis:
          pool:
              max-active: 8
              max-wait: 5000    # 最大阻塞等待时间5000ms
              max-idle: 8
              min-idle: 0


mybatis-plus:
    type-enums-package: edu.whu.model.common.enumerate

xy-nas-tools:
    knife4j:
        base-package: whu.edu.controller
        title: xyNasTools任务调度服务在线API文档
        description: xyNasTools任务调度服务在线API文档, 用于前后端联调
        version: 1.0
