### 查询任务列表: 正常情况
GET http://{{base-url}}:{{port}}/job/list?pageNum=1&pageSize=1
Content-Type: application/json
Authorization: Bearer {{adminToken}}

> {% client.test("testListJobs", () => {
    client.assert(response.status === 200)
    client.assert(response.body.total = 1)
}) %}

### 查询任务列表: 异常情况
GET http://{{base-url}}:{{port}}/job/list?pageNum=1&pageSize=1
Content-Type: application/json
Authorization: Bearer {{userToken}}

> {% client.test("testListJobsUnauthorized", () => {
    client.assert(response.status === 401)
}) %}

### 查询某个用户的任务列表
GET http://{{base-url}}:{{port}}/job/list/{{id}}
Content-Type: application/json
Authorization: Bearer {{userToken}}

> {% client.test("testListJobsById", () => {
    client.assert(response.status === 200)
    client.assert(response.body.total = 1)
}) %}

### 查询某个用户的任务列表: 非本人操作的异常情况
GET http://{{base-url}}:{{port}}/job/list/{{id}}
Content-Type: application/json
Authorization: Bearer {{adminToken}}

> {% client.test("testListJobsByIdUnauthorized", () => {
    client.assert(response.status === 401)
}) %}

### 添加任务: 正常情况
POST http://{{base-url}}:{{port}}/job/add
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "jobName": "测试任务",
  "jobGroup": "测试任务组",
  "invokeTarget": "http://127.0.0.1:12121/hello?name=wangwu",
  "cronExpression": "/1 * * * * ?",
  "misfirePolicy": "1",
  "concurrent": "0",
  "invokeMethod": "GET"
}

> {% client.test("testAddJob", () => {
    client.assert(response.status === 200)
}) %}