server:
  port: 12138

spring:
  application:
    name: anime-assistant-ttols
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # 数据库配置
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://lzynb.com.cn/yhy-yyds
    username: course-design
    password: course-design2023

mybatis-plus:
  type-enums-package: edu.whu.model.common.enumerate
  type-handlers-package: edu.whu.handler

xy-nas-tools:
  knife4j:
    base-package: edu.whu.controller
    title: xyNasTools任务调度服务在线API文档
    description: xyNasTools任务调度服务在线API文档, 用于前后端联调
    version: 1.0
  retry:
    maxAttempts: 3
    backoff:
      delay: 1000
      multiplier: 0